add IT for group
okta/okta-sdk-golang pull request #334
Opened 2022-10-07 20:13 UTC by duytiennguyen-okta

## Summary

Fixes #

## Type of PR

- [ ] Bug Fix (non-breaking fixes to existing functionality)
- [ ] New Feature (non-breaking changes that add new functionality)
- [ ] Documentation update
- [ ] Test Updates
- [ ] Other (Please describe the type)

## Test Information

- [ ] My PR required test updates 

Go Version:
Os Version:
OpenAPI Spec Version:

## Signoff
- [ ] I have submitted a CLA for this PR
- [ ] Each commit message explains what the commit does
- [ ] I have updated documentation to explain what my PR does
- [ ] My code is covered by tests if required
- [ ] I ran `make fmt` on my code
- [ ] I did not edit any automatically generated files

2022-10-12 23:35 UTC, monde requested changes

2022-10-12 23:35 UTC, monde commented on .generator/templates/group_test.go
> +	t.Run("get list group", func(t *testing.T) {
Some of the test runs didn't get updated with their name from "get list group" being used as a reference.
Lines 52, 56, 74

2022-10-13 01:25 UTC, monde commented on .generator/templates/main_test.go
> +	err = sweepGroupRules()
That is, to not return early if there is an error and try to each sweeper?

2022-10-13 15:01 UTC, duytiennguyen-okta commented on .generator/templates/main_test.go
> +	err = sweepGroupRules()
@monde not really no, I was just follow the v2 sweep example

2022-10-13 15:50 UTC, merged